# Site settings
title: Digital Avenue Tech Blog
email: digitalavenuelk@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The digital Avenue sole purpose is providing a comprehensive knowledge in Howtos, Tutorials, Guides, Tech Comparison and much more in the fast moving tech world. Digital Avenue empowers you the vast knowledge in the Information Technology Industry. You can learn Software Development, System Engineering, Latest IT News, Career Development Ideas, Tech Products Comparisons and much more. 
metadata:
    author: Dimuthu Daundasekara
    keywords: Digital Avenue,Digital,Linux,Linux Tutorials,Technology,Tech Guides,HowTos,How To,Redhat,CentOS,AWS,Cloud
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://digitalave.github.io" # the base hostname & protocol for your site
twitter_username: DigitalAvenue2
github_username:  digitalave
facebook: digitalavenuelk

# Plugins
plugins: [jekyll-paginate, jekyll-feed, jekyll-redirect-from]
whitelist: [jekyll-redirect-from]

# Build settings
markdown: kramdown

sass:
    sass_dir: _sass
    style: compressed

# Pagination
paginate: 10

collections:
    # Needed for our job board
    jobs:
        output: true
        permalink: /jobs/:path/
    # Tutorial Catagories
    catagory:
        output: true
        permalink: /category/:path

defaults:
  - scope:
      path: ""
      type: category
    values:
      layout: "category"

keep_files: [img]