source 'https://rubygems.org'
gem 'github-pages', group: :jekyll_plugins
gem 'jekyll'
gem 'jekyll-paginate'
gem 'jekyll-redirect-from'
gem 'rake'
gem 'rake-jekyll'
gem 'jekyll-feed'
gem 'mini_magick'
gem 'blur_image'
gem 'wdm'